#!/usr/bin/with-contenv bash

if [[ -z "${GATEWAY}" ]]; then
	# fall back to system nameserver if GATEWAY env variable is not set
	GATEWAY=$(grep nameserver /etc/resolv.conf | awk '{print $2}')
fi

TRANSMISSION_USERNAME=$USER TRANSMISSION_PASSWORD=$PASS /transmission-nat-pmp -gateway $GATEWAY